
# Should be equivalent to your list of C files, if you don't build selectively
SRC=$(wildcard *.c)

CFLAGS = -I. -L.

%.o : %.c
	gcc -c $(CFLAGS) $< -o $@

main: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main1: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main2: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main3: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main4: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main5: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main6: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main7: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main8: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main9: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main10: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main11: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main12: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main13: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main14: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main15: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main16: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main17: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main18: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main19: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

main20: $(SRC)
	gcc -o $@ $^ $(CFLAGS)

# https://stackoverflow.com/questions/170467/makefiles-compile-all-c-files-at-once
# https://stackoverflow.com/questions/3932895/makefile-aliases/3933012#3933012

